#define OPCION_INVALIDA -1

//TIPO DE ERRORES
#define ERROR_OPCION_INVALIDA 0
#define ERROR_NUMERO_INVALIDO 1
#define ERROR_DIVISION_POR_CERO 2
#define ERROR_FACTORIAL_NEGATIVO 3

//MINIMOS Y MAXIMOS
#define MAXIMO_CARACTERES 40

//TIPO DE MENU PRINCIPAL
#define MENU_SIN_OPERANDOS 0
#define MENU_SOLO_1ER_OPERANDO 1
#define MENU_AMBOS_OPERANDOS 2

//OPCIONES MENU PRINCIPAL
#define INGRESAR_1ER_OPERANDO 1
#define INGRESAR_2DO_OPERANDO 2
#define SUMA 3
#define RESTA 4
#define DIVISION 5
#define MULTIPLICACION 6
#define FACTORIAL 7
#define CALCULAR_TODAS 8
#define SALIR 9
